# Generated by Django 4.2.6 on 2023-10-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offshelf_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
            ],
        ),
    ]
