# Generated by Django 4.2.6 on 2023-10-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offshelf_app", "0002_iteminfo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="iteminfo",
            name="data",
        ),
        migrations.AddField(
            model_name="iteminfo",
            name="custom_field1",
            field=models.CharField(default="default val", max_length=100),
        ),
        migrations.AddField(
            model_name="iteminfo",
            name="custom_field2",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="iteminfo",
            name="description",
            field=models.TextField(default="hbbjb"),
        ),
        migrations.AddField(
            model_name="iteminfo",
            name="title",
            field=models.CharField(default="title", max_length=255),
        ),
    ]
