# Generated by Django 4.2.6 on 2023-10-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offshelf_app", "0003_remove_iteminfo_data_iteminfo_custom_field1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iteminfo",
            name="custom_field1",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="iteminfo",
            name="custom_field2",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="iteminfo",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="iteminfo",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
