# Generated by Django 4.2.6 on 2023-10-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offshelf_app", "0004_alter_iteminfo_custom_field1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="iteminfo",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="iteminfo",
            old_name="custom_field2",
            new_name="quantity",
        ),
        migrations.RenameField(
            model_name="iteminfo",
            old_name="description",
            new_name="type",
        ),
        migrations.RemoveField(
            model_name="iteminfo",
            name="custom_field1",
        ),
        migrations.AddField(
            model_name="iteminfo",
            name="expiry_date",
            field=models.BigIntegerField(default=123456789),
        ),
    ]
