# Generated by Django 4.2.6 on 2023-10-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offshelf_app", "0005_rename_title_iteminfo_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="iteminfo",
            name="image_file",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
