# Generated by Django 4.2.6 on 2023-10-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offshelf_app", "0006_iteminfo_image_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iteminfo",
            name="image_file",
            field=models.BinaryField(default=b""),
        ),
    ]
